import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const homepage = readFileSync(resolve(root, 'index.html'), 'utf8');
const confirmation = readFileSync(resolve(root, 'confirmation/index.html'), 'utf8');

function body(source) {
  return source.match(/<body[^>]*>([\s\S]*?)<\/body>/)?.[1] ?? '';
}

function header(source) {
  return body(source).match(/<header class="site-header">([\s\S]*?)<\/header>/)?.[1] ?? '';
}

function position(source, marker) {
  const index = source.indexOf(marker);
  assert.notEqual(index, -1, `Missing expected page marker: ${marker}`);
  return index;
}

test('both public pages use a centered logo-only header', () => {
  for (const [name, source] of [['homepage', homepage], ['confirmation', confirmation]]) {
    const content = header(source);
    assert.match(content, /class="brand"/u, `${name} header must retain the linked Kodara brand`);
    assert.equal((content.match(/<a\b/gu) ?? []).length, 1, `${name} header must contain only the brand link`);
    assert.doesNotMatch(content, /<nav\b|cta-btn|header-state/u, `${name} header must not contain navigation, an action, or status text`);
  }
});

test('homepage follows the approved qualification narrative', () => {
  const content = body(homepage);
  const orderedMarkers = [
    'class="site-hero"',
    'class="homepage-stats"',
    'class="search-demand-section"',
    'class="mechanism-features"',
    'class="case-studies"',
    'class="founder-highlight"',
    'class="faq"',
    'class="card cta"',
    'class="site-footer"',
  ];

  const positions = orderedMarkers.map((marker) => position(content, marker));
  assert.deepEqual(positions, [...positions].sort((a, b) => a - b), 'Homepage sections must follow the approved order');

  for (const removedSection of ['education-section', 'audience-section', 'credibility-section', 'proof-snapshot']) {
    assert.doesNotMatch(content, new RegExp(`<section class="${removedSection}"`), `${removedSection} must not remain in the visible homepage flow`);
  }
  assert.doesNotMatch(content, /class="section-cta"/u, 'Intermediate qualification actions must be removed');
});

test('homepage presents the supplied animated online-demand chart before the build process', () => {
  const content = body(homepage);
  const section = content.match(/<section class="search-demand-section"[\s\S]*?<\/section>/u)?.[0] ?? '';

  assert.match(section, /Health and wellness demand is exploding online\./u);
  assert.match(section, /People are already searching online for answers, options, and experts they can trust\./u);
  assert.match(section, /data-search-demand-chart/u);
  assert.match(section, /data-estimates-url="assets\/data\/search-estimates\.json"/u);
  assert.match(section, /data-cues-url="assets\/data\/motion-cues\.json"/u);
  assert.match(section, /<svg[^>]*data-search-demand-plot[^>]*role="img"[^>]*aria-labelledby="search-demand-keyword search-demand-description"/u);
  assert.match(section, /Illustrative estimates\. Search interest indexed to 2016 = 100\./u);
  assert.doesNotMatch(section, /<iframe|<canvas/u, 'The chart must remain native SVG');
  assert.match(homepage, /<script type="module" src="assets\/js\/search-demand-chart\.mjs"><\/script>/u);
  assert.ok(position(content, 'class="homepage-stats"') < position(content, 'class="search-demand-section"'));
  assert.ok(position(content, 'class="search-demand-section"') < position(content, 'class="mechanism-features"'));
});

test('homepage stat row uses the four approved verified figures', () => {
  const content = body(homepage);
  const stats = content.match(/<section class="homepage-stats"[\s\S]*?<\/section>/u)?.[0] ?? '';

  assert.equal((stats.match(/class="homepage-stat(?:\s[^"]*)?"/gu) ?? []).length, 4, 'Homepage needs exactly four stat cards');
  assert.match(stats, />350\+<\/strong>/u);
  assert.match(stats, />\$50M\+<\/strong>/u);
  assert.match(stats, />105,000\+<\/strong>/u);
  assert.match(stats, />30\+<\/strong>/u);
  assert.match(stats, /running their businesses online with Kodara/iu);
  assert.match(stats, /Revenue generated by our team for online knowledge-based products/iu);
  assert.match(stats, /Leads &amp; consultations generated by our team and used to train the Kodara AI model/iu);
  assert.match(stats, /Health, wellness, and medical modalities where we have helped clients create their AI/iu);
  assert.match(stats, /<article class="homepage-stat homepage-stat--compact">\s*<strong>105,000\+<\/strong>/u, 'The longest stat needs its compact display treatment');
});

test('homepage keeps the approved integrations and one final qualification action', () => {
  const content = body(homepage);
  assert.match(homepage, /https:\/\/t\.kodarahealth\.com\/v1\//u, 'Click tracking must remain in the page');
  assert.match(content, /id="vidalytics_embed_CA0308FsT4_Z8w5E"/u, 'The approved VSL must remain');
  assert.match(content, /id="kodara-triager"/u, 'The live qualification widget target must remain');
  assert.match(content, /https:\/\/embed\.kodara\.com\/v1\/widget\.js/u, 'The live qualification widget script must remain');

  const qualificationLinks = [...content.matchAll(/<a\b[^>]*class="[^"]*qualification-link[^"]*"[^>]*>/gu)].map((match) => match[0]);
  assert.equal(qualificationLinks.length, 1, 'Homepage must use one final qualification action outside the live widget');
  assert.match(qualificationLinks[0], /href="#kodara-triager"/u, 'The final qualification action must return to the live widget');
});

test('approved process and client proof remain visible', () => {
  const content = body(homepage);
  const demand = content.match(/<section class="search-demand-section"[\s\S]*?<\/section>/u)?.[0] ?? '';
  const process = content.match(/<section class="mechanism-features"[\s\S]*?<\/section>/u)?.[0] ?? '';
  const stories = content.match(/<section class="case-studies"[\s\S]*?<\/section>/u)?.[0] ?? '';
  const faq = content.match(/<section class="faq"[\s\S]*?<\/section>/u)?.[0] ?? '';
  assert.match(demand, /Health and wellness demand is exploding online\./u);
  assert.doesNotMatch(process, /\shidden(?:\s|>)/u, 'The three-step process must be visible');
  assert.doesNotMatch(process, /class="mechanism-demo"/u, 'The three-step process must not use decorative image boxes');
  assert.match(process, /Give us one hour a week\. We handle the build, launch, and beta-user onboarding\./u);
  assert.match(process, /Share what you know\./u);
  assert.match(process, /Review what we build\./u);
  assert.match(process, /Launch and onboard users\./u);
  assert.equal((process.match(/class="mechanism-step"/gu) ?? []).length, 3, 'Each process card needs a clear step label');

  assert.match(stories, /What happens when your expertise works without you\./u);
  assert.match(stories, /Each expert built an online business that depended less on their personal time\./u);
  assert.match(faq, /Everything you need to know before you apply\./u);
  assert.match(faq, /What we build, how it works, what we need from you, and what happens next\./u);

  const resultCards = [...stories.matchAll(/<article class="client-result-card">([\s\S]*?)<\/article>/gu)].map((match) => match[1]);
  assert.equal(resultCards.length, 2, 'Only Dr. Vora and Ashley should retain concise result summaries');
  assert.equal((stories.match(/class="client-result-points"/gu) ?? []).length, 2, 'Each result summary needs its own supporting facts');
  assert.equal((stories.match(/class="client-result-person"/gu) ?? []).length, 2, 'Each result summary needs a client identity row');
  assert.equal((stories.match(/class="client-result-avatar(?:\s[^"]*)?"/gu) ?? []).length, 2, 'Each result summary needs a circular client avatar');
  assert.match(stories, /class="client-result-avatar client-result-avatar--mirrored" src="assets\/testimonials\/amit-vora\.jpg"[^>]*alt="Amit N\. Vora"/u, 'Dr. Vora must use the approved mirrored portrait');
  assert.match(stories, /class="client-result-avatar client-result-avatar--mirrored" src="assets\/testimonials\/ashley-holly\.jpg"[^>]*alt="Ashley Holly"/u, 'Ashley must use the approved mirrored portrait');
  for (const card of resultCards) {
    assert.equal((card.match(/<li>/gu) ?? []).length, 2, 'Each result summary must contain exactly two supporting facts');
  }
  assert.match(stories, /class="testimonial-stars" aria-hidden="true">(?:<span>★<\/span>){5}<\/div>/u, 'The testimonial bridge must contain five decorative gold star icons');
  assert.match(stories, /I’m now on track to make double what I made last year\. My business feels consistent now, and I’m able to enjoy it more\./u, 'The testimonial bridge must use Sandra’s approved combined quote');
  assert.ok(position(stories, 'class="testimonial-spotlight"') < position(stories, 'class="case-support-grid"'), 'The featured quote must introduce the deeper video stories');
  assert.doesNotMatch(stories, /class="client-results-grid"/u, 'Result summaries should share the video-story grid instead of forming a separate section');
  const videoStories = stories.match(/<div class="case-support-grid" aria-label="Client stories and results">([\s\S]*?)<\/div>\s*<p class="proof-note"/u)?.[1] ?? '';
  assert.equal((videoStories.match(/<article class="case-support(?:\s[^"]*)?"/gu) ?? []).length, 3, 'Sandra, Dr. Mike, and Leanne need distinct video-story cards');
  assert.equal((videoStories.match(/<article class="client-result-card">/gu) ?? []).length, 2, 'Dr. Vora and Ashley must sit in the same proof grid as the videos');
  assert.match(videoStories, /<article class="case-support case-support--portrait"[^>]*>[\s\S]*?media-id="6oj2gj3wqt"/u, 'Sandra’s story must use the taller portrait-card treatment');
  assert.match(videoStories, /media-id="6oj2gj3wqt"/u, 'Sandra’s video must remain in the paired story grid');
  assert.match(videoStories, /class="case-media case-media--portrait-fit">\s*<div class="case-portrait-player">\s*<wistia-player media-id="6oj2gj3wqt"/u, 'Sandra’s portrait video must retain a dedicated 3:4 frame instead of being cropped into widescreen');
  assert.match(videoStories, /<video class="case-native-video"[^>]*src="assets\/testimonials\/dr-mike\.mp4"[^>]*poster="assets\/testimonials\/dr-mike-poster\.jpg"[^>]*preload="none"/u, 'Dr. Mike’s approved testimonial must use the web-optimized local video without preloading it');
  assert.match(videoStories, /His AI product was in testing within about 30 days\./u, 'Dr. Mike’s story must lead with the supported implementation milestone');
  assert.doesNotMatch(videoStories, /\$100,?000/u, 'Dr. Mike’s future revenue goal must not be presented as a testimonial result');
  assert.match(videoStories, /<article class="case-support case-support--wide"[^>]*>[\s\S]*?media-id="fay3lgo8op"/u, 'Leanne’s widescreen story must span the full desktop proof row');
  assert.match(stories, /30\+ patients enrolled in five weeks\./u);
  assert.match(stories, /Replaced in-person classes in two months\./u);

  for (const proof of ['Sandra Parker', 'Leanne Ellington', 'Dr. Vora', 'Ashley Holly']) {
    assert.match(content, new RegExp(proof.replace('.', '\\.')), `Client proof must retain ${proof}`);
  }
});
